# Generated by Django 3.0.8 on 2020-07-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=250)),
                ('location', models.TextField()),
                ('password', models.CharField(max_length=128)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
